EZP-31774: Main fixes after ux review
ezsystems/ezplatform-admin-ui pull request #1455
Opened 2020-08-21 13:29 UTC by lucasOsti

jira ref: https://jira.ez.no/browse/EZP-31774

2020-08-25 07:27 UTC, dew326 requested changes

2020-08-25 07:27 UTC, dew326 commented on src/bundle/Resources/public/scss/_custom.scss
> +$ibexa-color-maximum-black: #222222;
`maximum-black` doesn't sound like a proper name

2020-08-25 07:27 UTC, dew326 commented on src/bundle/Resources/public/scss/ui/modules/sub-items-list/_grid.view.item.scss
> +
```suggestion

```

2020-08-25 07:27 UTC, dew326 commented on src/bundle/Resources/public/scss/ui/modules/sub-items-list/_grid.view.item.scss
> +        width: 248px;
calcrem

2020-08-25 11:34 UTC, GrabowskiM requested changes
Almost in all occurences there is class `ez-pagination__spacing` without parent class, ony here it's done correctly: https://github.com/ezsystems/ezplatform-admin-ui/pull/1455/files#diff-e04f99099a5cc47cacd5fcd8956643f7R70

2020-08-25 11:34 UTC, GrabowskiM commented on src/bundle/Resources/public/scss/_custom.scss
> +$ibexa-color-maximum-black: #222222;
ibexa-color-blackest-black :P

2020-08-25 11:34 UTC, GrabowskiM commented on src/bundle/Resources/public/scss/_user-menu.scss
> +
empty line

2020-08-25 11:34 UTC, GrabowskiM commented on src/bundle/Resources/public/scss/mixins/_modals.scss
> +        padding: $modal-footer-padding;
bad indent

2020-08-25 11:34 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/account/notifications/list.html.twig
> +    <div class="row justify-content-center align-items-center ez-pagination__spacing">
I think there's no base class `ez-pagination` anywhere?

2020-08-25 13:18 UTC, GrabowskiM approved these changes

2020-08-26 06:19 UTC, dew326 requested changes

2020-08-26 06:19 UTC, dew326 commented on src/bundle/Resources/public/scss/ui/modules/sub-items-list/_grid.view.item.scss
> +    transition: all $ez-admin-transition;
transition is defined above

2020-08-26 06:19 UTC, dew326 commented on src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
> +                border: 2px solid $ibexa-color-primary;
calcRem

2020-08-26 07:10 UTC, merged