EZEE-3239: Exported ImageAsset classes as a base for DAM Connector
ezsystems/ezplatform-admin-ui pull request #1456
Opened 2020-08-24 12:55 UTC by ViniTou

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZEE-3239
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Unless there is different way to do this, I need those here:
https://github.com/ezsystems/ezplatform-connector-dam/pull/4

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2020-08-25 07:40 UTC, lucasOsti approved these changes

2020-08-31 10:40 UTC, dew326 requested changes

2020-08-31 10:40 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
> +            this.fieldContainer.addEventListener('ez-show-preview', () => this.showPreview());
I think `ez-show-preview` is too generic, I would make it more like: `ez-field-type-show-preview` or even give a possibility to fire custom event per "final" class not generic one for all use cases.

2020-09-08 13:10 UTC, dew326 approved these changes

2020-09-10 07:52 UTC, merged