EZEE-3215: changed selector container for tooltip to closest
ezsystems/ezplatform-admin-ui pull request #1507
Opened 2020-09-20 10:01 UTC by mateuszdebinski

| Question      | Answer
| ------------- | ---
| Tickets       | [EZEE-3215](https://jira.ez.no/browse/EZEE-3215)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-09-21 06:07 UTC, dew326 requested changes

2020-09-21 06:07 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
> +                    $(tooltipNode).closest(tooltipNode.dataset.tooltipContainerSelector) :
```suggestion
                    tooltipNode.closest(tooltipNode.dataset.tooltipContainerSelector) :
```

You don't have to use jQuery for closest.

2020-09-21 07:42 UTC, dew326 approved these changes

2020-09-21 07:44 UTC, konradoboza approved these changes

2020-09-21 08:03 UTC, GrabowskiM approved these changes

2020-09-21 08:53 UTC, lucasOsti approved these changes

2020-09-23 09:56 UTC, bogusez approved these changes

2020-09-24 08:40 UTC, merged

2020-09-24 08:41 UTC, adamwojs commented
Could you please merge up changes @mateuszdebinski?