EZEE-3271: Fixed styles for 'Send to review' action menu
ezsystems/ezplatform-admin-ui pull request #1519
Opened 2020-09-21 12:52 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZEE-3271
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-09-21 12:59 UTC, dew326 requested changes

2020-09-21 12:59 UTC, dew326 commented on src/bundle/Resources/public/scss/_buttons.scss
> +    .btn:not(.ez-btn--confirm-send-to-trash):not(.ez-btn--hide-confirm):not(.ez-btn--workflow-apply) {
Cannot be here, admin-ui should not have styles for workflow.

2020-09-22 08:23 UTC, GrabowskiM approved these changes

2020-09-22 08:26 UTC, dew326 approved these changes

2020-09-22 08:26 UTC, merged