EZP-31887: Added missing header informations in create/edit content/user
ezsystems/ezplatform-admin-ui pull request #1530
Opened 2020-09-23 12:18 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31887
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

![Screenshot from 2020-09-23 14-16-55](https://user-images.githubusercontent.com/24355391/94011351-8327a280-fda7-11ea-8188-6b7ba4d1ef13.png)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-09-23 13:00 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
> +{% block breadcrumbs %}{% endblock %}
is this block needed now?

2020-09-24 09:34 UTC, dew326 requested changes

2020-09-24 09:34 UTC, dew326 commented on src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
> -        <div class="ez-content-edit-page-title__description">{{ description }}</div>
Why content type description is removed? I think it should stay.

2020-09-24 11:17 UTC, GrabowskiM approved these changes

2020-09-24 11:24 UTC, dew326 requested changes

2020-09-24 11:24 UTC, dew326 commented on src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
> +                <div class="my-1">{{ content_type.description }}</div>
Removing `description` variable is kind of a BC break

2020-09-24 13:18 UTC, dew326 approved these changes

2020-09-24 14:11 UTC, merged