EZP-31951: Redesign modals
ezsystems/ezplatform-admin-ui pull request #1542
Opened 2020-09-29 12:08 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31951
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-09-29 14:04 UTC, GrabowskiM requested changes

2020-09-29 14:04 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/content/modal/draft_conflict.html.twig
>                          {% set number = conflicted_drafts|length %}
I have an impression that after removing this tag you have bad indents in next lines

2020-09-29 14:04 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/component/custom_dropdown.html.twig
> +<div class="ez-custom-dropdown__wrapper {% if class is defined %}{{ class }}{%endif%}" {% if source_selector is defined %}data-source-selector="{{ source_selector }}"{%endif%}>
couldn't it be just `class|default('')` insted of `{% if class is defined %}{{ class }}{%endif%}` ?

2020-09-29 14:04 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/component/custom_dropdown.html.twig
> +            <li data-value="" class="ez-custom-dropdown__item"{% if required and value is empty %} selected="selected"{% endif %}>{{ placeholder != '' ? (translation_domain is same as(false) ? placeh
Do not create nested ternary operators

2020-09-29 14:04 UTC, GrabowskiM commented on src/bundle/ui-dev/src/modules/common/popup/popup.component.js
> +                        {noHeader
couldn't it be single line?

2020-09-30 10:58 UTC, GrabowskiM approved these changes

2020-10-02 11:25 UTC, dew326 commented
Backend is also included here, original PR https://github.com/ezsystems/ezplatform-admin-ui/pull/1534
//cc @adamwojs

2020-10-02 11:28 UTC, adamwojs approved these changes

2020-10-02 11:30 UTC, dew326 approved these changes

2020-10-02 11:31 UTC, merged