EZP-31849 content edit screen improve design to display validation errors
ezsystems/ezplatform-admin-ui pull request #1572
Opened 2020-10-12 08:48 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31849
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-10-12 09:01 UTC, dew326 requested changes

2020-10-12 09:01 UTC, dew326 commented on src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
> +            content: '!';
I'm not sure if have `!` in new mockups?

2020-10-12 09:01 UTC, dew326 commented on src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
> +            <div class="ez-break-line"></div>
I'm not sure if adding some divs just to make a break line is a proper way.

2020-10-12 10:18 UTC, GrabowskiM requested changes

2020-10-12 10:18 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
> +                errorNodeSelectors: [`${SELECTOR_FIELD_NAME}`],
just `[SELECTOR_FIELD_NAME]`

2020-10-12 10:18 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
> +                errorNodeSelectors: [`${SELECTOR_FIELD_EMAIL}`],
as above

2020-10-12 10:18 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/fieldType/ezuser.js
> +                errorNodeSelectors: [`${SELECTOR_FIELD_USERNAME}`],
same as in first files, there are four occurenes in this file

2020-10-12 10:18 UTC, GrabowskiM commented on src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
> +
two new lines

2020-10-12 12:21 UTC, GrabowskiM approved these changes

2020-10-13 07:57 UTC, dew326 requested changes

2020-10-13 07:57 UTC, dew326 commented on src/bundle/Resources/public/scss/_forms.scss
> +.ez-break-line {
Seems like it is not needed anymore?

2020-10-13 09:11 UTC, dew326 approved these changes

2020-10-13 09:12 UTC, merged