Ezp 32075 redesign error page
ezsystems/ezplatform-admin-ui pull request #1635
Opened 2020-10-21 13:35 UTC by lucasOsti

jira ref: https://jira.ez.no/browse/EZP-32075

![Screenshot from 2020-10-21 15-34-28](https://user-images.githubusercontent.com/24355391/96727066-f1658200-13b2-11eb-9f90-a79288e1b019.png)

2020-10-21 13:36 UTC, lserwatka approved these changes

2020-10-22 10:20 UTC, GrabowskiM requested changes
General idea: maybe it would be good idea to make some base twig file for all xxx error pages? Most of structure is same in all cases

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/public/scss/_error-page.scss
> +        &--top-section {
I think it should be element instead of modifier

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/error_page/403.html.twig
> +        <div class="ez-error-page ez-error-page--top-section">
Should be element instead of modifier

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/error_page/403.html.twig
> +        <div class="ez-error-page ez-error-page--bottom-section">
Should be element instead of modifier

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/error_page/403.html.twig
> +
unnecessary newline

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig
> +        <div class="ez-error-page ez-error-page--top-section">
Should be element instead of modifier

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig
> +        <div class="ez-error-page ez-error-page--bottom-section">
Should be element instead of modifier

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/error_page/unknown.html.twig
> +        <div class="ez-error-page ez-error-page--top-section">
Should be element instead of modifier

2020-10-22 10:20 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/error_page/unknown.html.twig
> +        <div class="ez-error-page ez-error-page--bottom-section">
Should be element instead of modifier

2020-10-22 11:44 UTC, GrabowskiM approved these changes

2020-10-22 11:46 UTC, dew326 approved these changes

2020-10-22 11:46 UTC, merged