EZP-31968: Added spinner to UDW
ezsystems/ezplatform-admin-ui pull request #1642
Opened 2020-10-26 12:29 UTC by lucasOsti

jira ref: https://jira.ez.no/browse/EZP-31734

2020-10-26 12:32 UTC, dew326 requested changes

2020-10-26 12:32 UTC, dew326 commented on src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
> -        return null;
As far as I remember this check prevents displaying an empty branch when it is the last item in the tree.

2020-10-28 11:33 UTC, GrabowskiM approved these changes

2020-10-29 08:47 UTC, dew326 approved these changes

2020-10-29 12:38 UTC, bogusez approved these changes

2020-10-29 12:44 UTC, merged