EZEE-3419: Fixed providing empty object instead of empty array when no data set
ezsystems/ezplatform-admin-ui pull request #1680
Opened 2020-12-23 11:05 UTC by ViniTou

| Question      | Answer
| ------------- | ---
| Tickets       | EZEE-3419
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2020-12-23 11:16 UTC, lucasOsti requested changes

2020-12-23 11:16 UTC, lucasOsti commented on src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
> +            previewVisual.setAttribute('data-additional-data', additionalData);
`previewVisual.dataset.additionalData = additionalData` ?

2020-12-23 11:26 UTC, lucasOsti approved these changes

2020-12-23 12:01 UTC, GrabowskiM approved these changes

2020-12-28 12:38 UTC, micszo approved these changes
QA Approved on Ibexa Experience v3.3.0-rc1 with diffs.

2020-12-28 12:40 UTC, merged