EZP-32166: Base translation dropdown single selection issue
ezsystems/ezplatform-admin-ui pull request #1689
Opened 2021-01-11 12:03 UTC by GrabowskiM

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/EZP-32166
| Bug fix?      | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Ready for Code Review

2021-01-11 12:07 UTC, dew326 requested changes

2021-01-11 12:07 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
> +                selectedItems.forEach((item, key) => {
```suggestion
                selectedItems.forEach((item, index) => {
```

2021-01-11 13:33 UTC, dew326 approved these changes

2021-01-11 15:13 UTC, lucasOsti approved these changes

2021-01-13 09:30 UTC, bogusez approved these changes

2021-01-13 09:50 UTC, merged

2021-01-13 09:51 UTC, lserwatka commented
@dew326 could you merge it up.

2021-01-13 09:57 UTC, dew326 commented
@lserwatka done