EZP-32179: Add footer to platform when user is logged in
ezsystems/ezplatform-admin-ui pull request #1695
Opened 2021-01-21 10:51 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/EZP-32179
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-01-21 13:24 UTC, dew326 requested changes

2021-01-21 13:24 UTC, dew326 commented on src/bundle/Resources/public/scss/_general.scss
> +.ez-footer {
This deserves a separate file.

2021-01-21 13:24 UTC, dew326 commented on src/bundle/Resources/translations/forms.en.xliff
> -        <note>key: role.policy.siso_control_center.all_functions</note>
This probably should not be removed. It will remove translations in policy select.
cc @mikadamczyk

2021-01-21 16:11 UTC, GrabowskiM requested changes

2021-01-21 16:11 UTC, GrabowskiM commented on src/bundle/Resources/public/scss/_general.scss
> +.ez-info-view,
Personally I would add new single class to css and add this class to html instead of styling by all these 20 classes

2021-01-21 16:11 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/footer.html.twig
> +        <img class="ez-footer__brand-img" src="/bundles/ezplatformadminui/img/ibexa-wordmark.svg" alt="Ibexa" />
alt with no trans

2021-01-21 16:11 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/footer.html.twig
> +        <img class="ez-footer__brand-img" src="/bundles/ezplatformadminui/img/ibexa-wordmark.svg" alt="Ibexa" />
Also - use asset()

2021-01-22 08:40 UTC, lucasOsti commented on src/bundle/Resources/views/themes/admin/ui/footer.html.twig
> +        <img class="ez-footer__brand-img" src="/bundles/ezplatformadminui/img/ibexa-wordmark.svg" alt="Ibexa" />
> alt with no trans

Should I translate name of company?

2021-01-25 10:27 UTC, GrabowskiM approved these changes

2021-01-25 10:38 UTC, dew326 approved these changes

2021-01-26 13:41 UTC, dew326 approved these changes

2021-01-27 08:29 UTC, GrabowskiM approved these changes

2021-01-27 13:00 UTC, GrabowskiM approved these changes

2021-01-27 13:08 UTC, dew326 approved these changes

2021-01-28 09:37 UTC, bogusez approved these changes

2021-01-28 10:02 UTC, merged