EZEE-3435: [Image upload] no validation message for files bigger than 2mb
ezsystems/ezplatform-admin-ui pull request #1698
Opened 2021-01-28 13:02 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

![Screenshot from 2021-01-28 13-59-36](https://user-images.githubusercontent.com/24355391/106141922-18c9a900-6171-11eb-9cdf-dd7c3e9ec9a5.png)

- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-01-28 13:47 UTC, dew326 requested changes

2021-01-28 13:47 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
> +        showFileSizeNotice() {
This is a BC break

2021-01-28 13:47 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
> +                input.dispatchEvent(new CustomEvent('ez-invalid-file-size'));
This is a BC break

2021-02-01 08:56 UTC, dew326 approved these changes

2021-02-01 10:20 UTC, GrabowskiM approved these changes

2021-02-01 11:17 UTC, bogusez approved these changes

2021-02-01 11:29 UTC, merged