EZEE-3435: [Image upload] no validation message for files bigger than…
ezsystems/ezplatform-admin-ui pull request #1702
Opened 2021-02-01 13:16 UTC by lucasOsti

… 2mb

| Question      | Answer
| ------------- | ---
| Tickets       | 
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2021-02-01 15:01 UTC, dew326 requested changes

2021-02-01 15:01 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
> +
```suggestion

```

2021-02-01 15:01 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
> +    [...document.querySelectorAll(SELECTOR_FIELD) ].forEach((fieldContainer) => {
```suggestion
    [...document.querySelectorAll(SELECTOR_FIELD)].forEach((fieldContainer) => {
```

2021-02-02 06:02 UTC, dew326 approved these changes

2021-02-02 07:08 UTC, bogusez approved these changes

2021-02-02 08:01 UTC, merged

2021-02-02 08:02 UTC, lserwatka commented
Could you merge it up?

2021-02-02 09:42 UTC, lucasOsti commented
> Could you merge it up?

Done