EZEE-3479: As a developer I want to have reusable componenet for charts
ezsystems/ezplatform-admin-ui pull request #1705
Opened 2021-02-08 13:17 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | 
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2021-02-10 08:25 UTC, dew326 requested changes

2021-02-10 08:25 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +            if (this.type === 'line') {
`this.type` this is never set in this base class and this class definitely should not know what are the values of this properties

2021-02-10 15:10 UTC, GrabowskiM requested changes

2021-02-10 15:10 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                checkbox.style.backgroundColor = '#fff';
I would put colors to constants at the beginning of file

2021-02-11 08:14 UTC, dew326 requested changes

2021-02-11 08:14 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                type: this.getType(),
`getType` is not defined in this class

2021-02-11 08:14 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                    layout: this.layoutOptions(),
```suggestion
                    layout: this.getLayoutOptions(),
```
?

2021-02-11 08:14 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                    scales: this.scaleOptions(),
```suggestion
                    scales: this.getScaleOptions(),
```
?

2021-02-11 08:14 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/core/line.chart.js
> +        legendOptions(chart) {
```suggestion
        getLegendOptions(chart) {
```
?

2021-02-11 12:01 UTC, dew326 approved these changes

2021-02-17 09:57 UTC, tomaszszopinski approved these changes
QA approved on Ibexa dxp 3.3.1-dev with patch.

2021-02-17 13:27 UTC, merged