EC-359: Refactore chart classes
ezsystems/ezplatform-admin-ui pull request #1713
Opened 2021-02-26 08:11 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/EC-359
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-03-01 10:11 UTC, GrabowskiM requested changes

2021-03-01 10:11 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                const pluginTooltips = [];
```suggestion
                const pluginTooltips = datasets.map((dataset, i) => {
                    return (
                        chart.getDatasetMeta(i).data.map((activeSector, j) => {
                            return new Chart.Tooltip(
                                {
                                    dataValue: chart.data.datasets[i].data[j],
                                    _options: chart.options.tooltips,
                                    _active: activeSector,
                                },
                                chart
                            );
                        })
                    );
                });
```

2021-03-01 10:11 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                datasets.forEach((dataset, i) => {
do not use `i` in such cases

2021-03-01 10:11 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                        chart.getDatasetMeta(i).data.map((activeSector, j) => {
or `j`

2021-03-01 10:11 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/core/base.chart.js
> +                animation: {
why this order? It means you can't overwrite `animation`?

2021-04-29 11:16 UTC, lucasOsti commented
outdate

2021-04-29 11:16 UTC, closed without merging