Added danger font color
ezsystems/ezplatform-admin-ui pull request #1739
Opened 2021-04-19 10:38 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | 
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2021-04-19 12:36 UTC, tischsoic requested changes

2021-04-19 12:36 UTC, tischsoic commented on src/bundle/Resources/public/scss/_custom.scss
> +$ibexa-color-font-danger:#d92d42;
I am really sorry, but... :D 
```suggestion
$ibexa-color-font-danger: #d92d42;
```

2021-04-19 14:07 UTC, tischsoic approved these changes

2021-04-20 06:05 UTC, dew326 approved these changes

2021-04-21 08:30 UTC, GrabowskiM approved these changes

2021-05-14 10:18 UTC, tomaszszopinski approved these changes
QA approved on Ibexa Commerce 3.3.2-dev with diff.

2021-05-17 06:40 UTC, merged

2021-05-17 06:41 UTC, adamwojs commented
Could you please merge up changes @lucasOsti?

2021-05-17 06:54 UTC, ViniTou commented
I had merged it up as it dependency for page-builder & page-fieldtype PRs.