EZP-31602: Moving to trash confirmation modal is not updated after sub-items bulk move
ezsystems/ezplatform-admin-ui pull request #1744
Opened 2021-04-26 12:24 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/EZP-31602
| Related to |
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-04-27 06:27 UTC, dew326 requested changes

2021-04-27 06:27 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/admin.location.view.js
> +    const contentName = doc.querySelector('.ez-sil').dataset.contentName;
Don't think this should be in the subitems div. This should be stored in the modal itself to be independent.

2021-04-27 10:53 UTC, GrabowskiM requested changes

2021-04-27 10:53 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/admin.location.view.js
> +            modalSendToTrashButton.classList.toggle('disabled', false);
remove instead of toggle

2021-04-27 10:53 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/admin.location.view.js
> +            modalSendToTrashButton.toggleAttribute('disabled', false);
removeattribute instead of toggleattribute

2021-04-28 08:24 UTC, tischsoic requested changes

2021-04-28 08:24 UTC, tischsoic commented on src/bundle/Resources/public/js/scripts/admin.location.view.js
> +    const refreshTrashModal = (event) => {
I wonder, maybe we should put these changes here:
https://github.com/ezsystems/ezplatform-admin-ui/blob/1.5/src/bundle/Resources/public/js/scripts/admin.trash.js

2021-04-28 09:40 UTC, tischsoic approved these changes

2021-04-28 12:15 UTC, GrabowskiM approved these changes

2021-04-29 06:13 UTC, dew326 approved these changes

2021-05-05 11:06 UTC, kacper-wieczorek-ibexa approved these changes
QA Approve - tested on 2.5
Tests on v3 after merge-up

2021-05-05 11:10 UTC, lserwatka commented
@mnocon same here, it is failing.

2021-05-05 14:07 UTC, merged

2021-05-05 14:07 UTC, lserwatka commented
You can merge it up.