IBX-186: The top button of side menus gets hidden at the bottom of the page
ezsystems/ezplatform-admin-ui pull request #1763
Opened 2021-05-26 13:13 UTC by GrabowskiM

| Question      | Answer
| ------------- | ---
| Tickets       | IBX-186
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-05-26 13:26 UTC, dew326 requested changes
I think we can do better if it comes to naming. I suggested some names, feel free to enhance them.

2021-05-26 13:26 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
> +    const setHeightOnScrollAndResize = () => {
```suggestion
    const setContainerHeightTimeout = () => {
```
?

2021-05-26 13:26 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
> +        resizeAndScrollTimeout = setTimeout(setContainerHeight, RESIZE_AND_SCROLL_TIMEOUT);
```suggestion
        setContainerHeightTimeout = setTimeout(setContainerHeight, RESIZE_AND_SCROLL_TIMEOUT);
```
?

2021-05-26 13:26 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
> +    const setHeightOnResizeAndScroll = () => {
```suggestion
    const addListeners = () => {
```
?

2021-05-26 13:26 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
> +    const resetHeightOnResizeAndScroll = () => {
```suggestion
    const removeListeners = () => {
```
?

2021-05-27 10:52 UTC, dew326 commented on src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
> +                        resetHeightOnResizeAndScroll();
Error function not found?

2021-05-27 12:14 UTC, tischsoic approved these changes

2021-05-28 06:01 UTC, dew326 approved these changes

2021-05-28 07:25 UTC, lucasOsti approved these changes

2021-05-29 10:50 UTC, merged

2021-05-29 10:51 UTC, lserwatka commented
You can merge it up.