IBX-455: Added selected content from bookmarks to the top of list contents
ezsystems/ezplatform-admin-ui pull request #1768
Opened 2021-06-01 10:42 UTC by mateuszdebinski

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-455](https://issues.ibexa.co/browse/IBX-455)
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2021-06-01 13:55 UTC, barw4 commented on src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
> +            $columnLocationIdBefore = (int) $locationPath[$locationPathLast - 1];
the ternary operator could be used here

2021-06-02 10:23 UTC, mateuszdebinski commented on src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
> +        $columnLocationIdBefore = (int) $locationPath[$locationPathIndex];
This is not initial Column but last, I change this variable name to `$lastColumnLocationId`

2021-06-02 10:24 UTC, mateuszdebinski commented on src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
> +            $index = array_search($locationId, array_map(static function ($location) {
This is not Location, it's array

2021-06-14 08:02 UTC, webhdx approved these changes

2021-06-14 08:05 UTC, konradoboza approved these changes

2021-06-14 08:06 UTC, ViniTou reviewed
I think we should have all that new code wrapped into private method that describes whats going on here. As for now i see search, some shifts and I still dont know why (aside from PR title.).

2021-06-14 08:10 UTC, damianz5 approved these changes

2021-06-14 08:40 UTC, Steveb-p requested changes
> I think we should have all that new code wrapped into private method that describes whats going on here. As for now i see search, some shifts and I still dont know why (aside from PR title.).

I second to that. It's confusing enough that it shouldn't be merged in this form.

2021-06-14 08:54 UTC, ciastektk approved these changes

2021-06-14 09:12 UTC, alongosz approved these changes

2021-06-14 09:13 UTC, mikadamczyk approved these changes

2021-06-14 09:19 UTC, ViniTou approved these changes

2021-06-16 12:52 UTC, bogusez approved these changes

2021-06-17 06:39 UTC, merged

2021-06-17 06:39 UTC, lserwatka commented
You can merge it up now