[WIP] IBX-579: Behat coverage for user with CT limitation adding location
ezsystems/ezplatform-admin-ui pull request #1783
Opened 2021-06-18 14:12 UTC by micszo

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-579](https://issues.ibexa.co/browse/IBX-579)
| Bug fix?      | no
| New feature?  | no (new test case)
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Admin UI part of the test checking whether user with Content Type limitation on content/create policy can add another location.

Related PRs:
https://github.com/ezsystems/BehatBundle/pull/185

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2021-06-29 14:21 UTC, mnocon requested changes
We can't hardcode the root Content Item name, it will fail on different editions.

Other remarks are rather nitpicks, but imho there's no need to divide the location adding action into two separate steps.

2021-06-30 07:22 UTC, micszo commented on src/lib/Behat/BusinessContext/ContentViewContext.php
> +        $contentItemPage->addLocation();
Thanks for the review! All should be applied in https://github.com/ezsystems/ezplatform-admin-ui/pull/1783/commits/66d05021b1ce32420f48da72bbaec4dc189e25ba.

2021-06-30 07:26 UTC, mnocon approved these changes
Looks good!

2021-06-30 08:03 UTC, bogusez approved these changes

2021-07-01 09:45 UTC, micszo commented
PR for 4.0: https://github.com/ezsystems/ezplatform-admin-ui/pull/1789

2021-07-01 13:01 UTC, merged