IBX-615: As an Editor, I want to see redesigned checkbox and radio buttons in all states
ezsystems/ezplatform-admin-ui pull request #1793
Opened 2021-07-05 13:02 UTC by GrabowskiM

JIRA ref: https://issues.ibexa.co/browse/IBX-615

2021-07-06 07:10 UTC, dew326 requested changes

2021-07-06 07:10 UTC, dew326 commented on src/bundle/Resources/public/scss/_inputs.scss
> +    appearance: none;
not sure if this should be on all inputs or just checkbox/radio

2021-07-06 08:28 UTC, lucasOsti commented on src/bundle/Resources/public/scss/_inputs.scss
>      transition: all 0.2s $ibexa-admin-transition;
`$ibexa-admin-transition-duration`

2021-07-06 10:01 UTC, tischsoic requested changes

2021-07-06 10:01 UTC, tischsoic commented on src/bundle/Resources/public/scss/_inputs.scss
> +                &:after {
```suggestion
                &::after {
```
ref: https://developer.mozilla.org/en-US/docs/Web/CSS/::after#syntax

2021-07-06 12:32 UTC, tischsoic commented on src/bundle/Resources/public/scss/_inputs.scss
> +        border-color: $ibexa-color-primary;
Not all active inputs have this border colour. Actually, not sure if any? Checkboxes do not have `:active` state, do they?

2021-07-06 12:38 UTC, tischsoic commented on src/bundle/Resources/public/scss/_inputs.scss
> +        cursor: default;
```suggestion
        cursor: not-allowed;
```

2021-07-07 07:29 UTC, lucasOsti approved these changes

2021-07-07 08:51 UTC, tischsoic approved these changes

2021-07-07 08:56 UTC, dew326 approved these changes

2021-07-07 11:37 UTC, merged