IBX-620: Redesigned ezauthor
ezsystems/ezplatform-admin-ui pull request #1847
Opened 2021-08-11 11:36 UTC by dew326

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-620
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-08-11 12:50 UTC, GrabowskiM requested changes

2021-08-11 12:50 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
> +            }
```suggestion
            bulkDeleteButton.toggleAttribute('disabled', !isAnyCheckboxSelected);
```

2021-08-11 12:50 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezauthor.html.twig
> +    <label class="ibexa-label form-label">{{ 'ezauthor.Email'|trans|desc('Email') }}</label>
```suggestion
        <label class="ibexa-label form-label">{{ 'ezauthor.name'|trans|desc('Name') }}</label>
        <label class="ibexa-label form-label">{{ 'ezauthor.Email'|trans|desc('Email') }}</label>
```

2021-08-11 13:52 UTC, lucasOsti approved these changes

2021-08-12 06:30 UTC, tischsoic commented on src/bundle/Resources/translations/messages.en.xliff
> +      <trans-unit id="91cee9d11eeed40768d4e5270d91cd5165f4562f" resname="ezobjectrelationlist.limit">
Were all these translations missing? Do we want to add them all in this PR?

2021-08-12 06:30 UTC, tischsoic commented on src/bundle/Resources/translations/messages.en.xliff
> +        <source>(max. %limit%)</source>
Were all these translations missing? Do we want to add them all in this PR?

2021-08-12 06:46 UTC, tischsoic approved these changes

2021-08-12 07:15 UTC, GrabowskiM approved these changes

2021-08-12 07:17 UTC, merged