IBX-431: Allowed interception of canceling the draft version edit
ezsystems/ezplatform-admin-ui pull request #1876
Opened 2021-08-27 09:48 UTC by Nattfarinn

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-431
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Rebase with 2.3 after merging: ~https://github.com/ezsystems/ezplatform-admin-ui/pull/1878~ Done.

There cancel button (`X`) was a plain link and it was not possible to intercept and react to the action on the backend side.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-08-30 10:06 UTC, adamwojs requested changes
Code style needs to be fixed here.

2021-08-30 10:06 UTC, adamwojs commented on src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
> +                   }) }}"
Could you please extract 

```
path('ezplatform.content.draft.edit.cancel', {
     'contentId': content.id,
     'referrerLocationId': referrer_location.id,
     'versionNo': content.versionInfo.versionNo,
     'languageCode': language.languageCode
 })
```

value to variable ? This should improve readability

2021-08-30 12:34 UTC, Nattfarinn commented
@adamwojs Code style is OK, our fixer configuration is outdated (we're not eZ Systems anymore).

2021-08-31 07:48 UTC, ViniTou approved these changes

2021-08-31 07:48 UTC, ViniTou commented on src/bundle/Controller/ContentEditController.php
> +        return $response ?? $this->redirectToRoute('_ez_content_view', [
You could use `\EzSystems\EzPlatformAdminUiBundle\Controller\Controller::redirectToLocation`

2021-08-31 07:48 UTC, ViniTou commented on src/bundle/Resources/config/routing.yaml
> +ezplatform.content.draft.edit.cancel:
```suggestion
ibexa.content.draft.edit.cancel:
```

2021-08-31 08:22 UTC, mikadamczyk approved these changes

2021-08-31 09:05 UTC, ciastektk approved these changes

2021-08-31 11:44 UTC, adamwojs approved these changes

2021-08-31 15:30 UTC, micszo approved these changes

2021-08-31 15:30 UTC, merged