IBX-963: Buttons on Trash page are hidden on medium resolutions
ezsystems/ezplatform-admin-ui pull request #1888
Opened 2021-09-03 10:13 UTC by GrabowskiM

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-963
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-09-03 10:55 UTC, dew326 approved these changes

2021-09-06 11:07 UTC, lucasOsti requested changes

2021-09-06 11:07 UTC, lucasOsti commented on src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
> +    <table class="ibexa-table table ibexa-table__draft-conflict {{ (is_draft and have_to_paginate ? 'mb-3' : '') }}">
you don't have an `ibexa-table` parent so i think it should either be `ibexa-draft-conflict` or `ibexa-table--draft-conflict`

2021-09-06 11:07 UTC, lucasOsti commented on src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
> +        <tbody
maybe one line?:)

2021-09-06 11:07 UTC, lucasOsti commented on src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
> +</div>
new line

2021-09-08 09:13 UTC, tischsoic commented on src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
> +    <div class="ibexa-scrollable-wrapper">
Do we want to make it an option?

2021-09-09 06:59 UTC, tischsoic commented on src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
> +    <div class="ibexa-scrollable-wrapper">
I think you didn't understand me. I was thinking about adding an option for 3rd party to disable with default value `true`.

2021-09-10 07:43 UTC, lucasOsti approved these changes

2021-09-10 10:59 UTC, tischsoic approved these changes

2021-09-10 11:08 UTC, merged