IBX-1023: Fixed instant filter input styles
ezsystems/ezplatform-admin-ui pull request #1920
Opened 2021-09-23 10:46 UTC by dew326

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-1023
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-09-23 13:59 UTC, GrabowskiM requested changes

2021-09-23 13:59 UTC, GrabowskiM commented on src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
> +                        <input type="text" class="ez-instant-filter__input ibexa-input ibexa-input--text form-control" placeholder="{{ ('Type to refine') }}" value="" />
I know it's not yours, but it would be nice to add translation to this placeholder

2021-09-24 08:00 UTC, GrabowskiM approved these changes

2021-09-24 09:12 UTC, lucasOsti approved these changes

2021-09-24 13:12 UTC, lucasOsti approved these changes

2021-09-24 15:05 UTC, tischsoic approved these changes

2021-09-27 08:46 UTC, merged