IBX-1096: Changed border from table to table header
ezsystems/ezplatform-admin-ui pull request #1922
Opened 2021-09-23 12:20 UTC by dew326

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-1096
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-09-23 13:53 UTC, GrabowskiM requested changes

2021-09-23 13:53 UTC, GrabowskiM commented on src/bundle/Resources/public/scss/_tables.scss
> +        font-size: calculateRem(18px);
You can use $ibexa-text-font-size-large

2021-09-23 13:59 UTC, GrabowskiM approved these changes

2021-09-24 09:11 UTC, lucasOsti approved these changes

2021-09-24 13:12 UTC, lucasOsti approved these changes

2021-09-24 15:03 UTC, tischsoic commented on src/bundle/Resources/public/scss/_tables.scss
> -.ez-table {
This wasn't deleted before because we still have (AFAIK) `ez-table--list`, which were not redesigned during table redesign.

2021-09-27 06:34 UTC, tischsoic approved these changes

2021-09-27 08:49 UTC, merged