Fixed content always being translated using a base translation
ezsystems/ezplatform-admin-ui pull request #1935
Opened 2021-09-28 14:14 UTC by mateuszbieniek

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-1079
| Bug fix?      | yes

Due to a `placeholder` setting set to `false` for `base_language` ChoiceType, `<select>` field with Languages available as a Base Translation always used the first option on the list, when submitted empty.

Changing `placeholder` to `true` resolves the "HTML" issue, but uncovers some underlying issues:
- When BaseLanguage is `null`, `ibexa.content.translate_with_location.proxy` route generates without the last `fromLanguageCode` part, and URL is matched against `ibexa.content.translate_with_location` with exception "Can't find Language `proxy`". This PR fixes this by changing order in `routing.yaml` so in this case `ibexa.content.translate_with_location.proxy` takes precedense.
- `ContentProxyCreateDraftListener:translate` always sets field values for the struct, therefore even when `fromLanguage` is set to `null`, main language values are used. This is fixed by adding `if ($fromLanguageCode !== null)` check before setting fields in the Struct.

In addition to the original issue, the same fix for translating Content Types is used.

2021-09-29 13:44 UTC, mikadamczyk requested changes
Maybe a good idea will be to add a comment in `routing.yaml` that we are relying on the order of routings. Or, we could exclude "proxy" as a language in requirements. And for 4.0 we should provide a better solution to not rely on routes order or requirements.

2021-11-18 13:40 UTC, mikadamczyk approved these changes

2021-11-18 13:48 UTC, Steveb-p approved these changes
> And for 4.0 we should provide a better solution to not rely on routes order or requirements.

I second to that.

2021-11-18 20:53 UTC, adamwojs approved these changes

2021-11-18 20:54 UTC, adamwojs commented
@mateuszbieniek You can move this PR to QA

2021-11-23 12:37 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 3.3.13-dev.

2021-11-23 12:53 UTC, mateuszbieniek commented
pinging @mikadamczyk :)

2021-11-23 13:11 UTC, merged

2021-11-23 13:12 UTC, mikadamczyk commented
@mateuszbieniek you can merge up and to ibexa

2021-11-23 15:38 UTC, mateuszbieniek commented
merged to ibexa: https://github.com/ibexa/admin-ui/commit/6f36566da0f66bad1657d71660319bcc95b8a6a3