IBX-1455: Redesign Content Tree for OSS
ezsystems/ezplatform-admin-ui pull request #2007
Opened 2021-11-16 12:25 UTC by GrabowskiM

https://issues.ibexa.co/browse/IBX-1455

2021-11-17 09:35 UTC, lucasOsti requested changes

2021-11-17 09:35 UTC, lucasOsti commented on src/bundle/Resources/views/themes/admin/content/location_view.html.twig
> +    <div class="ez-content-tree-container"
Shouldn't `ibexa` prefix be here?

2021-11-17 09:35 UTC, lucasOsti commented on src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
> +        const width = this.isTreeCollapsed() ? 320 : 96;
could you please put these values ​​in a variable whose name says what it is

2021-11-17 10:06 UTC, dew326 requested changes

2021-11-17 10:06 UTC, dew326 commented on src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tree.scss
> +        width: initial !important;
I think the rule should be removed when content tree is refactored not only todo ;)

2021-11-17 15:58 UTC, tischsoic commented on src/bundle/Resources/public/js/scripts/admin.content.tree.js
> +    doc.body.addEventListener('ibexa-tb-rendered:ibexa-content-tree', removeContentTreeContainerWidth);
Maybe `ibexa-tb-rendered:ibexa-content-tree` is correct, but it feels strange :D

2021-11-17 15:58 UTC, tischsoic commented on src/bundle/Resources/public/js/scripts/admin.content.tree.js
>      const btn = doc.querySelector('.ibexa-btn--toggle-content-tree');
```suggestion
    const contentTreeToggleBtn = doc.querySelector('.ibexa-btn--toggle-content-tree');
```

2021-11-17 15:58 UTC, tischsoic commented on src/bundle/Resources/views/themes/admin/content/location_view.html.twig
> +    {% set content_tree_width_style = 'width: %spx;'|format(content_tree_width) %}
We can also do:
```suggestion
    {% set content_tree_width_style = "width: #{content_tree_width}px;" %}
```

2021-11-18 09:19 UTC, lucasOsti requested changes

2021-11-18 09:19 UTC, lucasOsti commented on src/bundle/Resources/public/scss/ui/modules/content-tree/_header.scss
> +        font-size: calculateRem(18px);
```suggestion
        font-size: $ibexa-text-font-size-large;
```

2021-11-18 09:19 UTC, lucasOsti commented on src/bundle/Resources/public/scss/ui/modules/content-tree/_list.item.scss
> +        > #{$list-item}__row {
do we really need a sass variable here?

2021-11-18 10:57 UTC, dew326 approved these changes

2021-11-19 12:49 UTC, closed without merging