IBX-1514: Removed validation of Content Types in UDW filter
ezsystems/ezplatform-admin-ui pull request #2015
Opened 2021-11-25 17:40 UTC by barw4

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-1514](https://jira.ez.no/browse/IBX-1514)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Removing it may feel wrong but that's how the 'normal' Search module works. This change will match Search module behavior.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-11-26 07:24 UTC, dew326 requested changes

2021-11-26 07:24 UTC, dew326 commented on src/bundle/ui-dev/src/modules/universal-discovery/components/content-type-selector/content.type.selector.js
> -import { AllowedContentTypesContext } from '../../universal.discovery.module';
I'm not convinced of this approach.
`AllowedContentTypesContext` stores configuration for UDW which content types are allowed to be chosen from UDW, that's why we filter possible content types in search. And I think it should stay the same.
I think the problem is in the configuration/listeners themselves.

2021-11-29 07:54 UTC, mikadamczyk approved these changes

2021-11-29 08:38 UTC, Steveb-p requested changes

2021-11-29 08:38 UTC, Steveb-p commented on src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
> +        if (in_array($event->getConfigName(), $event::READ_SPECIFIC_CONFIGURATIONS)) {
```suggestion
        if (in_array($event->getConfigName(), $event::READ_SPECIFIC_CONFIGURATIONS), true) {
```

2021-11-29 08:38 UTC, Steveb-p commented on src/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypes.php
> +        if (!in_array($event->getConfigName(), $event::READ_SPECIFIC_CONFIGURATIONS)) {
```suggestion
        if (!in_array($event->getConfigName(), $event::READ_SPECIFIC_CONFIGURATIONS), true) {
```

2021-11-29 08:38 UTC, Steveb-p commented on src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
> +    public const READ_SPECIFIC_CONFIGURATIONS = ['richtext_embed', 'richtext_embed_image', 'browse'];
I see this only used in context of checking whether the config name matches or does not match entries in this array.

If that's the case, I think it's more appropriate to introduce an event method instead?

2021-12-01 10:16 UTC, tischsoic approved these changes

2021-12-01 10:18 UTC, konradoboza approved these changes

2021-12-02 14:01 UTC, Steveb-p commented on src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
> +    public const READ_SPECIFIC_CONFIGURATIONS = ['richtext_embed', 'richtext_embed_image', 'browse'];
```suggestion
    private const READ_SPECIFIC_CONFIGURATIONS = ['richtext_embed', 'richtext_embed_image', 'browse'];
```
:smiling_imp:

2021-12-02 14:14 UTC, Steveb-p approved these changes

2021-12-07 08:50 UTC, piotrbisaga commented
QA approved.
Check on Ibexa Commerce 3.3.x-dev.

2021-12-07 12:06 UTC, merged

2021-12-07 12:07 UTC, mikadamczyk commented
@barw4 you could merge it up and to ibexa

2021-12-07 14:35 UTC, barw4 commented
Merge request to `ibexa/admin-ui/main`.