EZEE-3213: Added verification if the user has section/view permission
ezsystems/ezplatform-admin-ui pull request #2016
Opened 2021-11-25 19:40 UTC by mateuszdebinski

| Question      | Answer
| ------------- | ---
| Tickets       | [EZEE-3213](https://issues.ibexa.co/browse/EZEE-3213)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Verification of permission according to other forms in our platform

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-11-26 07:54 UTC, webhdx requested changes
This is not a reliable way to check permissions. Simply use `PermissionResolver` and inject additional variable to the Twig template.

2021-11-26 08:56 UTC, webhdx requested changes

2021-11-26 08:56 UTC, webhdx commented on src/bundle/Controller/TrashController.php
> +            'can_section' => $this->isGranted(new Attribute('section', 'view')),
Please use proper name: `can_view_section`.

2021-11-26 09:04 UTC, webhdx approved these changes

2021-11-26 09:10 UTC, konradoboza approved these changes

2021-11-26 09:10 UTC, mikadamczyk approved these changes

2021-11-26 09:21 UTC, dew326 approved these changes

2021-11-29 10:46 UTC, kacper-wieczorek-ibexa approved these changes
QA - approved. Tested on 3.3.12 experience, commerce.
It is possible to open trash as editor.

2021-11-29 10:51 UTC, merged

2021-11-29 10:59 UTC, lserwatka commented
@mateuszdebinski you must merge it to ibexa/admin-ui:main