Ibx 1465 priority language siteaccess v3
ezsystems/ezplatform-admin-ui pull request #2018
Opened 2021-11-26 13:34 UTC by mateuszdebinski

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-1465](https://issues.ibexa.co/browse/IBX-1465)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-11-26 13:50 UTC, adamwojs requested changes

2021-11-26 13:50 UTC, adamwojs commented on src/lib/UI/Config/Provider/Languages.php
> +    private $siteAccessService;
You shouldn't rely on concrete implementation. Use corresponding interface instead.

2021-11-26 13:59 UTC, adamwojs approved these changes

2021-11-26 14:01 UTC, konradoboza approved these changes

2021-11-26 14:52 UTC, mikadamczyk approved these changes

2021-11-29 06:45 UTC, dew326 approved these changes

2021-11-29 10:50 UTC, bogusez approved these changes

2021-11-29 10:52 UTC, merged

2021-11-29 10:59 UTC, lserwatka commented
@mateuszdebinski you must merge it to ibexa/admin-ui:main