IBX-857: Added call invalidateSize on each map when tab clicked and if tab contains any map
ezsystems/ezplatform-admin-ui pull request #2047
Opened 2022-05-23 14:27 UTC by mateuszdebinski

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-857](https://issues.ibexa.co/browse/IBX-857)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Because the map is not visible immediately (display:none;) the map can't compute the correct position, therefore the call invalidateSize(true); has been added for maps when changing the tab, thanks to which it is able to calculate the correct position

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2022-05-24 07:29 UTC, dew326 approved these changes

2022-05-24 09:52 UTC, tischsoic requested changes

2022-05-24 09:52 UTC, tischsoic commented on src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
> +            maps.forEach(map => map.invalidateSize(true));
code formatting (Prettier)
```suggestion
            maps.forEach((map) => map.invalidateSize(true));
```

2022-05-24 09:52 UTC, tischsoic commented on src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
> +        const element = doc.querySelector(id);
```suggestion
        const tabPaneSelector = event.target.getAttribute('href');
        const tabPane = doc.querySelector(tabPaneSelector);
```

2022-05-24 09:52 UTC, tischsoic commented on src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
> +    $('.ez-tabs a').on('shown.bs.tab', (event) => {
We avoid using elements selectors and tend to use CSS classes instead:
```suggestion
    $('.ez-tabs .nav-link').on('shown.bs.tab', (event) => {
```

2022-05-24 11:08 UTC, OstafinL approved these changes

2022-05-24 13:17 UTC, tischsoic approved these changes

2022-05-25 14:23 UTC, GrabowskiM approved these changes

2022-05-26 10:10 UTC, bogusez approved these changes

2022-05-26 10:19 UTC, merged