IBX-2964: Flatpickr widget localization
ezsystems/ezplatform-admin-ui pull request #2059
Opened 2022-08-08 23:31 UTC by barw4

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-3334](https://issues.ibexa.co/browse/IBX-3334)
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

The language will be picked up from the User's Back Office settings.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2022-08-09 06:09 UTC, konradoboza commented
It seems the JIRA issue link is wrong.

2022-08-17 11:57 UTC, GrabowskiM requested changes

2022-08-17 11:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/widgets/flatpickr.js
> +    flatpickr.localize(flatpickrLanguage);
```suggestion

    flatpickr.localize(flatpickrLanguage);

```

2022-08-17 11:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/widgets/flatpickr.js
> +    const flatpickrLanguage = flatpickrLanguages[backOfficeLanguage] || flatpickrLanguages.default;
```suggestion
    const flatpickrLanguage = flatpickrLanguages[backOfficeLanguage] ?? flatpickrLanguages.default;

```

2022-08-17 11:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/widgets/flatpickr.js
> +    const backOfficeLanguage = eZ.adminUiConfig.backOfficeLanguage;
```suggestion
    const { backOfficeLanguage } = eZ.adminUiConfig;

```

2022-08-17 11:57 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/widgets/flatpickr.js
> +(function (eZ, flatpickr) {
```suggestion
(function (global, doc, eZ, flatpickr) {
```
these two parameters (global and doc) should be always included, even if they're not used at the moment, as for consistency and readability they should be as first two args, and we shouldn't change order of params in the future... I think. @dew326

2022-08-17 13:25 UTC, GrabowskiM requested changes

2022-08-17 13:25 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/widgets/flatpickr.js
> +
```suggestion
```
Sorry, my mistake in previous suggestion, I added one new line too much

2022-08-17 13:25 UTC, GrabowskiM commented on src/bundle/Resources/public/js/scripts/widgets/flatpickr.js
> +})(global, doc, window.eZ, window.flatpickr);
```suggestion
})(window, window.document, window.eZ, window.flatpickr);

```

2022-08-17 13:47 UTC, OstafinL approved these changes

2022-08-17 13:49 UTC, konradoboza approved these changes

2022-08-17 13:49 UTC, konradoboza commented on src/lib/UI/Config/Provider/BackOfficeLanguage.php
> +class BackOfficeLanguage implements ProviderInterface
```suggestion
final class BackOfficeLanguage implements ProviderInterface
```

2022-08-18 14:08 UTC, GrabowskiM approved these changes

2022-08-22 11:01 UTC, mikadamczyk approved these changes

2022-08-22 11:19 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 3.3

2022-08-22 11:34 UTC, merged