IBX-3681 - Added selectedLanguage update on location change in UDW
ezsystems/ezplatform-admin-ui pull request #2065
Opened 2022-08-22 11:49 UTC by mateuszbieniek

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-3681](https://issues.ibexa.co/browse/IBX-3681)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no

When a location is clicked inside UDW the languageSelected is set by
```
    const [selectedLanguage, setSelectedLanguage] = useState(preselectedLanguage || firstLanguageCode);
```
Unfortunately, `useState` only sets the value of the hook and won't update it with the next elements clicked, which can end up in a different Language used by Content on the Fly, when the default element in the Language Selected form is the one that user wants to use (so no `onClick` event).
The change introduced ensures that `languageSelected` const has a proper value set.

2022-08-22 11:54 UTC, GrabowskiM requested changes

2022-08-22 11:54 UTC, GrabowskiM commented on src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
> +    }, [preselectedLanguage, firstLanguageCode]);
```suggestion
    }, [preselectedLanguage, firstLanguageCode]);
    
```

2022-08-22 13:02 UTC, GrabowskiM approved these changes

2022-08-22 13:03 UTC, lucasOsti approved these changes

2022-08-23 10:14 UTC, tomaszszopinski commented
After patch appliance original error is fixed, but 404 error appears when Article CT is opened (step 8 in Jira)

https://user-images.githubusercontent.com/59650405/186133281-fc7361b3-a77c-4128-8b4b-414da66ead63.mov

.

2022-08-23 11:06 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 3.3 commerce.

2022-08-23 11:16 UTC, mateuszbieniek commented
> After patch appliance original error is fixed, but 404 error appears when Article CT is opened (step 8 in Jira)
> 2065_1.mov
> 
> .

Issue not related to the fix:
https://issues.ibexa.co/browse/IBX-3713
The fix only makes it easier to surface.

2022-08-23 11:50 UTC, merged