IBX-3814: Added checks if the field to upload is type ezimage to add alternative text
ezsystems/ezplatform-admin-ui pull request #2082
Opened 2022-12-05 09:55 UTC by mateuszdebinski

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-3814](https://issues.ibexa.co/browse/IBX-3814)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Related PR: https://github.com/ezsystems/ezplatform-rest/pull/99

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2022-12-06 09:22 UTC, GrabowskiM requested changes

2022-12-06 09:22 UTC, GrabowskiM commented on src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
> +                .catch(() => window.eZ.helpers.notification.showErrorNotification('Cannot get content type by identifier'))
Translation

2022-12-06 09:22 UTC, GrabowskiM commented on src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
> +                            mainLanguageCode: languageCode || parentInfo.language,
```suggestion
                            mainLanguageCode: languageCode ?? parentInfo.language,
```

2022-12-06 09:22 UTC, GrabowskiM commented on src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
> +                .catch(() => window.eZ.helpers.notification.showErrorNotification('Cannot create content structure'));
Translation

2022-12-07 10:55 UTC, Gengar-i approved these changes

2022-12-09 07:17 UTC, dew326 approved these changes

2022-12-09 08:57 UTC, GrabowskiM approved these changes

2022-12-14 09:30 UTC, lucasOsti approved these changes

2022-12-14 13:11 UTC, bogusez commented
Regression tests passed: 
https://github.com/ibexa/experience/pull/118
https://github.com/ibexa/commerce/pull/175
https://github.com/ibexa/content/pull/65

2022-12-14 13:30 UTC, bogusez approved these changes

2022-12-14 13:51 UTC, merged