IBX-6592: Allowed `Location` to be a part of permission check for Object State assignment
ezsystems/ezplatform-admin-ui pull request #2112
Opened 2023-11-07 16:07 UTC by barw4

| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-6592](https://issues.ibexa.co/browse/IBX-6592)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

2023-11-28 08:48 UTC, ViniTou commented on src/bundle/Resources/config/routing.yaml
> -    path: /state/contentstate/update/{contentInfoId}/group/{objectStateGroupId}
that's a bc break, I guess we should create new route and deprecate that one.

2023-11-28 08:48 UTC, ViniTou commented on src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
> +                    function () use ($objectStateGroup, $location) {
```suggestion
                    function () use ($objectStateGroup, $location): array {
```

2023-11-28 08:48 UTC, ViniTou commented on src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
> +                            function (ObjectState $objectState) use ($location) {
```suggestion
                            function (ObjectState $objectState) use ($location): bool {
```

2023-11-30 12:24 UTC, Nattfarinn requested changes
This is not correct approach. We can't make our permission layer to behave differently if used from UI and used as API.

2023-11-30 15:16 UTC, barw4 commented
> This is not correct approach. We can't make our permission layer to behave differently if used from UI and used as API.

@Nattfarinn where exactly does it behave differently than what we have in the API?

2023-12-01 09:13 UTC, Nattfarinn commented
> @Nattfarinn where exactly does it behave differently than what we have in the API?

This additional argument is used only in `ibexa/admin-ui`. I know this was done to keep BC, but existing API calls that won't use `Location` will behave differently and would force everyone to update all their API calls (what about REST calls?) to use additional parameter to make it work the same. If we insist on keeping BC here (ping @alongosz), we should be able to do that without changes to API.

This could/should be solved in https://github.com/ezsystems/ezplatform-kernel/blob/1.3/eZ/Publish/Core/Limitation/SubtreeLimitationType.php by handling special case (maybe check `$targets` for `ObjectState`?) but this would need at least @alongosz decision/expertise/omniscience.

2023-12-19 14:55 UTC, webhdx commented
We put more thought into this change and we can't change the API to facilitate Locations only to be used as a part of Permission check. I think the proper solution is to remove `LocationSubtree` limitation from `state:assign` policy and fix the documentation. It was never working correctly and I believe it was added by a mistake since Object State API doesn't work with Locations at all.

2023-12-20 12:08 UTC, closed without merging